# projeto_etl/dbt_projeto/dbt_project.yml
name: 'dbt_projeto'
version: '1.0.0'
config-version: 2

profile: 'dbt_projeto'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  raw_database: RAW_DATA
  raw_schema: BR_ENERGY_DATA

# Bloco corrigido sem o '+'
models:
  dbt_projeto:
    staging:
      materialized: view
    marts:
      dimensions:
        materialized: table
      facts:
        materialized: table